# https://dev.azure.com/home-assistant

trigger:
  batch: true
  branches:
    include:
    - master
    - dev
  tags:
    include:
    - '*'
    exclude:
    - untagged*
pr:
  - dev
variables:
  - name: versionHadolint
    value: 'v1.16.3'
  - name: versionBuilder
    value: '4.4'
  - group: docker
  - group: wheels

jobs:

- job: 'Tox'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.7'
    inputs:
      versionSpec: '3.7'
  - script: pip install tox
    displayName: 'Install Tox'
  - script: tox
    displayName: 'Run Tox'


- job: 'Hadolint'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: sudo docker pull hadolint/hadolint:$(versionHadolint)
    displayName: 'Install Hadolint'
  - script: |
      sudo docker run --rm -i \
        -v $(pwd)/.hadolint.yaml:/.hadolint.yaml:ro \
        hadolint/hadolint:$(versionHadolint) < Dockerfile
    displayName: 'Run Hadolint'


- job: 'Black'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.7'
    inputs:
      versionSpec: '3.7'
  - script: pip install black
    displayName: 'Install black'
  - script: black --check builder
    displayName: 'Run Black'


- template: .azure/azp-template-wheels.yml
  parameters:
    name: '37_Alpine39'
    python: '3.7-alpine3.9'


- template: .azure/azp-template-wheels.yml
  parameters:
    name: '37_Alpine310'
    python: '3.7-alpine3.10'


- job: 'VersionValidate'
  condition: or(startsWith(variables['Build.SourceBranch'], 'refs/tags'), eq(variables['Build.SourceBranchName'], 'dev'))
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.7'
    inputs:
      versionSpec: '3.7'
  - script: |
      setup_version="$(python setup.py -V)"
      branch_version="$(Build.SourceBranchName)"

      if [ "${branch_version}" == "dev" ]; then
        exit 0
      elif [ "${setup_version}" != "${branch_version}" ]; then
        echo "Version of tag ${branch_version} don't match with ${setup_version}!"
        exit 1
      fi
    displayName: 'Check version of branch/tag'


- job: 'Release'
  dependsOn:
  - 'Tox'
  - 'Hadolint'
  - 'VersionValidate'
  timeoutInMinutes: 120
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    maxParallel: 2
    matrix:
      37-Alpine39:
        buildPython: '3.7-alpine3.9'
        buildArgs: ''
      37-Alpine310:
        buildPython: '3.7-alpine3.10'
        buildArgs: '--release-tag'
  steps:
  - script: sudo docker login -u $(dockerUser) -p $(dockerPassword)
    displayName: 'Docker hub login'
  - script: sudo docker pull homeassistant/amd64-builder:$(versionBuilder)
    displayName: 'Install Builder'
  - script: |
      sudo docker run --rm --privileged \
        -v ~/.docker:/root/.docker \
        -v /run/docker.sock:/run/docker.sock:rw -v $(pwd):/data:ro \
        homeassistant/amd64-builder:$(versionBuilder) \
        --builder-wheels $(buildPython) --all \
        $(buildArgs) --version $(Build.SourceBranchName) \
        -t /data --docker-hub homeassistant
    displayName: 'Build Release'
