# https://dev.azure.com/home-assistant

trigger:
  patch: true
  branches:
    include:
      - master
pr: none
resources:
  repositories:
    - repository: azure
      type: github
      name: "home-assistant/ci-azure"
      endpoint: "home-assistant"

stages:
  - stage: "Wheels"
    jobs:
      - template: templates/azp-job-wheels.yaml@azure
        parameters:
          jobName: "Wheels_37_Alpine310"
          builderVersion: "dev-3.7-alpine3.10"
          builderApk: "build-base;libffi-dev;openssl-dev"
          wheelsRequirement: "requirements_all.txt"
          preBuild:
            - script: |
                cat requirements.txt requirements_build.txt > requirements_all.txt
              displayName: "Prepare requirements"
      - template: templates/azp-job-wheels.yaml@azure
        parameters:
          jobName: "Wheels_37_Alpine311"
          builderVersion: "dev-3.7-alpine3.11"
          builderApk: "build-base;libffi-dev;openssl-dev"
          wheelsRequirement: "requirements_all.txt"
          preBuild:
            - script: |
                cat requirements.txt requirements_build.txt > requirements_all.txt
              displayName: "Prepare requirements"
      - template: templates/azp-job-wheels.yaml@azure
        parameters:
          jobName: "Wheels_38_Alpine310"
          builderVersion: "dev-3.8-alpine3.10"
          builderApk: "build-base;libffi-dev;openssl-dev"
          wheelsRequirement: "requirements_all.txt"
          preBuild:
            - script: |
                cat requirements.txt requirements_build.txt > requirements_all.txt
              displayName: "Prepare requirements"
      - template: templates/azp-job-wheels.yaml@azure
        parameters:
          jobName: "Wheels_38_Alpine311"
          builderVersion: "dev-3.8-alpine3.11"
          builderApk: "build-base;libffi-dev;openssl-dev"
          wheelsRequirement: "requirements_all.txt"
          preBuild:
            - script: |
                cat requirements.txt requirements_build.txt > requirements_all.txt
              displayName: "Prepare requirements"
