# https://dev.azure.com/home-assistant

trigger:
  batch: true
  branches:
    include:
    - master
    - dev
  tags:
    include:
    - '*'
    exclude:
    - untagged*
pr:
  - dev
variables:
  - name: versionHadolint
    value: 'v1.16.3'
  - name: versionBuilder
    value: '4.4'
  - group: docker
resources:
  repositories:
    - repository: azure
      type: github
      name: 'home-assistant/ci-azure'
      endpoint: 'home-assistant'

jobs:

- job: 'Tox'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '3.7'
  - script: pip install tox
    displayName: 'Install Tox'
  - script: tox
    displayName: 'Run Tox'


- job: 'Hadolint'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: sudo docker pull hadolint/hadolint:$(versionHadolint)
    displayName: 'Install Hadolint'
  - script: |
      sudo docker run --rm -i \
        -v $(pwd)/.hadolint.yaml:/.hadolint.yaml:ro \
        hadolint/hadolint:$(versionHadolint) < Dockerfile
    displayName: 'Run Hadolint'


- template: templates/azp-job-wheels.yaml@azure
  parameters:
    jobName: 'Wheels_Alpine39'
    builderVersion: 'dev-3.7-alpine3.9'
    builderApk: 'build-base;libffi-dev;openssl-dev'
    wheelsRequirement: 'requirements_all.txt'
    preBuild:
    - script: |
        cat requirements.txt requirements_build.txt > requirements_all.txt
      displayName: 'Prepare requirements'

- template: templates/azp-job-wheels.yaml@azure
  parameters:
    jobName: 'Wheels_Alpine310'
    builderVersion: 'dev-3.7-alpine3.10'
    builderApk: 'build-base;libffi-dev;openssl-dev'
    wheelsRequirement: 'requirements_all.txt'
    preBuild:
    - script: |
        cat requirements.txt requirements_build.txt > requirements_all.txt
      displayName: 'Prepare requirements'


- template: templates/azp-job-version.yaml@azure
  parameters:
    ignoreDev: true


- job: 'Release'
  dependsOn:
  - 'Tox'
  - 'Hadolint'
  - 'VersionValidate'
  timeoutInMinutes: 120
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    maxParallel: 2
    matrix:
      37-Alpine39:
        buildPython: '3.7-alpine3.9'
        buildArgs: ''
      37-Alpine310:
        buildPython: '3.7-alpine3.10'
        buildArgs: '--release-tag'
  steps:
  - script: sudo docker login -u $(dockerUser) -p $(dockerPassword)
    displayName: 'Docker hub login'
  - script: sudo docker pull homeassistant/amd64-builder:$(versionBuilder)
    displayName: 'Install Builder'
  - script: |
      sudo docker run --rm --privileged \
        -v ~/.docker:/root/.docker \
        -v /run/docker.sock:/run/docker.sock:rw -v $(pwd):/data:ro \
        homeassistant/amd64-builder:$(versionBuilder) \
        --builder-wheels $(buildPython) --all \
        $(buildArgs) --version $(Build.SourceBranchName) \
        -t /data --docker-hub homeassistant
    displayName: 'Build Release'
