# https://dev.azure.com/home-assistant

trigger:
  branches:
    include:
      - master
  tags:
    include:
      - "*"
pr: none
variables:
  - name: versionBuilder
    value: "4.4"
  - group: docker
resources:
  repositories:
    - repository: azure
      type: github
      name: "home-assistant/ci-azure"
      endpoint: "home-assistant"

stages:
  - stage: "Validate"
    jobs:
      - template: templates/azp-job-version.yaml@azure
        parameters:
          ignoreDev: true

  - stage: "Release"
    jobs:
      - job: "Release"
        pool:
          vmImage: "ubuntu-latest"
        strategy:
          matrix:
            37-Alpine310:
              buildPython: "3.7-alpine3.10"
              buildArgs: ""
            37-Alpine311:
              buildPython: "3.7-alpine3.11"
              buildArgs: ""
            38-Alpine310:
              buildPython: "3.8-alpine3.10"
              buildArgs: ""
            38-Alpine311:
              buildPython: "3.8-alpine3.11"
              buildArgs: "--release-tag"
        steps:
          - script: sudo docker login -u $(dockerUser) -p $(dockerPassword)
            displayName: "Docker hub login"
          - script: sudo docker pull homeassistant/amd64-builder:$(versionBuilder)
            displayName: "Install Builder"
          - script: |
              if [ "$(Build.SourceBranchName)" == "master" ]; then
                version="dev"
              else
                version="$(Build.SourceBranchName)"
              fi

              sudo docker run --rm --privileged \
                -v ~/.docker:/root/.docker \
                -v /run/docker.sock:/run/docker.sock:rw -v $(pwd):/data:ro \
                homeassistant/amd64-builder:$(versionBuilder) \
                --builder-wheels $(buildPython) --all \
                $(buildArgs) --version "${version}" \
                -t /data --docker-hub homeassistant
            displayName: "Build Release"
