name: Self

on:
  pull_request:
    branches:
      - master

jobs:
  self:
    name: TEST
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Check out the repository
        uses: actions/checkout@v2

      - name: ğŸ‘· Build wheels
        uses: ./
        with:
          test: true

      - name: ğŸ‘· Build wheels
        uses: ./
